output_schema:
  name: UserDetail
  prompt: "Extracting a user"
  properties:
    - title: name
      type: str
      prompt: "What is the user's name?"
    - title: friends 
      type: str[]
      prompt: "some friends."

input_schema:
  name: Request
  properties:
    - title: show 
      type: str

prompt:
  - role: system
    content: "You are character generator"
  - role: user
    content: "Create a person from this show: {{show}}"

model: gpt-4-turbo